export const statementsTypes = {
    STATEMENT_PRINT : 0,
    STATEMENT_EXPR : 1,
    STATEMENT_VAR_DEC : 2,
    STATEMENT_BLOCK : 3,
    STATEMENT_IF : 4,
    STATEMENT_WHILE : 5,
    STATEMENT_FUNC : 6,
    STATEMENT_RETURN: 7
}